notifications:
  email: false

sudo: required
dist: trusty

language: c
compiler: gcc

addons:
  apt:
    packages:
      - gettext

script:
  - cd po && for i in *.po; do echo -ne "${i%.po}:\t"; msgfmt --statistics -c -o ${i%.po}.gmo $i; done

